#!/usr/bin/env node
// Renders data/design/tokens.json to site/src/styles/tokens.css and computes
// every contrast ratio in the record. The rendered file is committed, and
// tools/check_tokens.mjs fails CI when it is stale, so the CSS the site runs on
// and the record a reader can open are the same numbers. No dependencies.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

export const root = join(dirname(fileURLToPath(import.meta.url)), "..");
export const RECORD = join(root, "data", "design", "tokens.json");
export const OUTPUT = join(root, "site", "src", "styles", "tokens.css");

export function load() {
  return JSON.parse(readFileSync(RECORD, "utf8"));
}

// WCAG 2 relative luminance and contrast ratio.
function channel(c) {
  const v = c / 255;
  return v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4;
}
export function luminance(hex) {
  const n = parseInt(hex.slice(1), 16);
  return 0.2126 * channel(n >> 16) + 0.7152 * channel((n >> 8) & 255) + 0.0722 * channel(n & 255);
}
export function contrast(a, b) {
  const [l1, l2] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (l1 + 0.05) / (l2 + 0.05);
}

// Every pair in the record, in both themes. Plate colours are fixed.
export function ratios(t) {
  const out = [];
  for (const pair of t.colour.pairs) {
    for (const theme of ["light", "dark"]) {
      const palette = { ...t.colour[theme], ...t.colour.plate };
      const fg = palette[pair.fg];
      const bg = palette[pair.bg];
      if (!fg || !bg) throw new Error(`pair ${pair.fg} on ${pair.bg}: unknown token`);
      out.push({ ...pair, theme, ratio: Math.round(contrast(fg, bg) * 100) / 100 });
    }
  }
  return out;
}

const block = (selector, entries, indent = "") =>
  `${indent}${selector} {\n${entries.map(([k, v]) => `${indent}  --${k}: ${v};`).join("\n")}\n${indent}}`;

export function render(t = load()) {
  const r = ratios(t);
  const line = (p) => {
    const l = r.find((x) => x.fg === p.fg && x.bg === p.bg && x.theme === "light").ratio.toFixed(2);
    const d = r.find((x) => x.fg === p.fg && x.bg === p.bg && x.theme === "dark").ratio.toFixed(2);
    return `     ${p.fg.padEnd(13)} on ${p.bg.padEnd(7)} ${l.padStart(6)} / ${d.padStart(6)}${p.text ? "" : "   decorative, never text"}`;
  };
  const motionDefault = t.motion.tokens.map((m) => [m.name, m.default]);
  const motionReduced = t.motion.tokens.filter((m) => m.default !== m.reduced).map((m) => [m.name, m.reduced]);
  // The name column is measured rather than fixed, because role names are
  // longer than the mechanism names they replaced and a hardcoded width put
  // the value column inside the name.
  const nameWidth = Math.max(11, ...t.motion.tokens.map((m) => m.name.length + 2));
  const table = t.motion.tokens.map((m) => `     ${("--" + m.name).padEnd(nameWidth)} ${m.default.padEnd(28)} ${m.reduced.padEnd(8)} ${m.used_by}`);
  return [
    "/* Generated by tools/tokens.mjs from data/design/tokens.json. Do not edit;",
    "   edit the record and run `node tools/tokens.mjs`. CI fails when this file",
    "   is stale. Light is the base and lives on bare :root, so the un-stamped",
    "   document, the default system setting, always has a full palette. The",
    "   dark blocks only redefine; nothing is defined for the first time inside",
    "   a media query or a data attribute block.",
    "",
    "   Contrast, computed, light / dark:",
    ...t.colour.pairs.map(line),
    "",
    "   Motion, default and reduced, a decision per movement:",
    ...table,
    `     scroll      ${t.motion.scroll.default.padEnd(28)} ${t.motion.scroll.reduced}`,
    "*/",
    block(":root", [
      ...Object.entries(t.colour.light),
      ...Object.entries(t.colour.plate),
      ...Object.entries(t.type),
      ...Object.entries(t.grid),
      ...motionDefault,
      ["_", null],
    ].filter(([, v]) => v !== null)).replace("\n}", "\n  color-scheme: light dark;\n}"),
    "@media (prefers-color-scheme: dark) {",
    block(':root:not([data-theme="light"])', Object.entries(t.colour.dark), "  "),
    "}",
    block(':root[data-theme="dark"]', Object.entries(t.colour.dark)).replace("\n}", "\n  color-scheme: dark;\n}"),
    ':root[data-theme="light"] {\n  color-scheme: light;\n}',
    "@media (prefers-reduced-motion: reduce) {",
    block(':root:not([data-motion="full"])', motionReduced, "  "),
    "}",
    block(':root[data-motion="reduce"]', motionReduced),
    "@media (prefers-reduced-motion: no-preference) {",
    `  :root:not([data-motion="reduce"]) {\n    scroll-behavior: ${t.motion.scroll.default};\n  }`,
    "}",
    "",
  ].join("\n");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(OUTPUT, render());
  console.log(`tokens: wrote ${OUTPUT}`);
}
